In [65]:
import joblib
import numpy as np
memory = joblib.Memory("C:/TEMP/features/memory/")
memory.clear()

@memory.cache(auto_shelve=True)
def large_array(x):
    return np.ones((1000,10000))

@memory.cache(auto_shelve=True)
def double_array(a):
    return a*2



In [68]:
%%time
a1 = large_array(1)


Wall time: 2 ms


In [69]:
%%time
a2 = large_array(2)


Wall time: 3 ms


In [74]:
np.testing.assert_array_equal( a1.get(), a2.get() )

In [75]:
def show_input_cached(func, *inp):
    func_id, arg_id = func._get_output_identifiers(*inp)
    path = [func_id, arg_id]
    output = func(*inp)
    cached = func.store_backend.load_item(path)
    print("input : ", *inp)
    print("input id : ", arg_id)
    print("output : ", output)
    print("output loaded : ", output.get())
    print("cached : ", cached)

In [81]:
%%time
show_input_cached(double_array, a)



input :  MemorizedResult(location="C:/TEMP/features/memory/joblib", func="__main__-C%3A-Users-i56574-Documents-Gratuiciels-Google Drive-DataScience-DSSP9-projet-02-model-__ipython-input__\large_array", args_id="d3ffa92536e9b2aeb96c6d0e11ccd857")
input id :  25197f0f75bb3c6f28873f1ba9612e7e
output :  MemorizedResult(location="C:/TEMP/features/memory/joblib", func="__main__-C%3A-Users-i56574-Documents-Gratuiciels-Google Drive-DataScience-DSSP9-projet-02-model-__ipython-input__\double_array", args_id="e3f6c43b79b87de5030ae22f867234dc")
output loaded :  [[2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 ...
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]]
cached :  e3f6c43b79b87de5030ae22f867234dc
Wall time: 111 ms


In [85]:
%%time
show_input_cached(double_array, a.get())

input :  [[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
input id :  e3f6c43b79b87de5030ae22f867234dc
output :  MemorizedResult(location="C:/TEMP/features/memory/joblib", func="__main__-C%3A-Users-i56574-Documents-Gratuiciels-Google Drive-DataScience-DSSP9-projet-02-model-__ipython-input__\double_array", args_id="e3f6c43b79b87de5030ae22f867234dc")
output loaded :  [[2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 ...
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]]
cached :  [[2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 ...
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]]
Wall time: 521 ms


In [94]:
%%time
double_array(a).get()

Wall time: 106 ms


array([[2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       ...,
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.]])

In [96]:
%%time
double_array(a.get()).get()

Wall time: 327 ms


array([[2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       ...,
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.]])

In [101]:
%%time
d = double_array(a2)

Wall time: 3 ms


In [93]:
%%time
d.get()

Wall time: 139 ms


array([[2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       ...,
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.]])

In [106]:
(d.get() == double_array.func(a.get())).all()

True